name: Merge branch
on:
  pull_request_review:
    types: [dismissed, edited, submitted]

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"
        with:
          ref: main

      - name: Merge
        run: |
          git fetch
          git merge origin/feat/update-readme
          git push origin main